### ISSUE TITLE
Lectures from 1st year should not be built

### ISSUE THREAD

**Issue by territhing** [hse-tex/hse-tex#127]
@DarkKeks может, имеет смысл перестать собирать пдф для техов с первого курса?
Туда же все равно никто не будет коммитить.

**Comment by DarkKeks** [comment]
Ну тут две стороны вопроса :)

- publish сейчас собирает только то, в чем есть дифф, то есть на сайт все попадает быстро
- build собирает совсем всё, чтобы случайно чего-нибудь не сломать

Я думаю что в build в мастере все еще имеет смысл собирать всё, чтобы быть уверенным, что все доки собираются (все равно никто не ждет быстрой сборки в мастере)

А вот в ПР видимо сделаю быструю сборку

**Comment by DarkKeks** [comment]
Но там все равно не меньше двух минут сборка, потому что texlive весит 2гб, и кажется 2 минуты уходит на то чтобы спуллить докер образ с ним

**Comment by territhing** [comment]
> А вот в ПР видимо сделаю быструю сборку
Ну я так и хотел, в принципе

**Comment by DarkKeks** [comment]
Чет я херню закоммитил

**Comment by DarkKeks** [comment]
Мне пока лень нормальное решение делать, временно уберу старые доки из `documents.yml`

**Comment by LoDThe** [comment]
Псс, тут каникулы как раз, можно заняться :+1:

**Comment by DarkKeks** [comment]
> Псс, тут каникулы как раз, можно заняться 👍
> ![image](https://user-images.githubusercontent.com/4996880/102487999-74861a00-407c-11eb-9e3f-37a16dbf4e17.png)

Ля какой

**Comment by DarkKeks** [comment]
Закоммитил исправление и вернул старые доки
Понаблюдаю за ПР пару дней, потом закрою тикет

**Comment by DarkKeks** [comment]
Вроде работает как надо
