### ISSUE TITLE
Поизучать возможность использовать latexmk для получения зависимостей документа

### ISSUE THREAD

**Issue by DarkKeks** [hse-tex/hse-tex#129]
Кажется latexmk может отдать список файлов, изменение которых может приводить к пересборке документа.
Стоило бы поизучать и заменить мои костыли но это))

**Comment by LoDThe** [comment]
Да, стоило бы, занялся бы кто-то...

**Comment by DarkKeks** [comment]
У latexmk есть -deps или -dependents, но они выводят что-то странное (.div файл), более того, ему нужно собрать документ чтобы это посчитать, поэтому смысла в этом мало

Других способов честно получить зависимости я не нашел :(
