### ISSUE TITLE
Прикреплять в ПР дифф документов

### ISSUE THREAD

**Issue by DarkKeks** [hse-tex/hse-tex#133]
Было бы удобно видеть в ПР, что именно изменилось в пдф без необходимости сравнивать их руками или, опять же руками, загружать их на какой-нибудь сторонний сервис.

Думаю поможет избежать неожиданных изменений.
при этом мы и так уже собираем пдф, построить дифф ничего не стоит.

**Comment by territhing** [comment]
Кажется, что для этого достаточно создать шаблон для пул-реквестов и отдельный гайд для контрибьюторов.

**Comment by lodthe** [comment]
— Да?

— Алё!

— Да да?

— Ну как там с деньгами?

— А?

— Как с деньгами-то там?

— Чё с деньгами?

— Чё?

— Куда ты звонишь?

— Тебе звоню.

— Кому?

— Ну тебе.

— Кому тебе?

— А вот тебе вот.

— Ты кто такой?

— Михал Палыч.

— Какой Михал Палыч?

— Терентьев.

— Такого не знаю, ты ошибся номером, друг.

— Кто?

— Ты.

— Чё с деньгами?

— Какими деньгами?

— Ну которые я внес в капитал.

— Куда?

— В капитал прожиточного минимума.

— Ты пьяный или кто, сынок?

— Я тре.. Я Михал Палыч Терентьев.

— Кто такой?

— Пьяный.

— Вот именно, ну и все, завяжи лямку, ёбана в рот.

— Куда… Чё завязать?

— Завяжи лямку!

— А чё ты кричишь?

— Да ничего!

— Алё!

— Да.

— Ну чё там?

— Чего?!

— Как с деньгами обстоят во… Обстоит вопрос?

— С какими деньгами?

— Которые я вложил в капитал.

— В какой капитал?

— Прожиточного минимума.

— Какой?

— В смысле в какой?

— Ты куда звонишь?! По какому номеру звонишь?

— По твоему номеру.

— Ты, сынок!

— Чё?!

— Сынок ёбаный!

— Чё?

— Ты куда звонишь?!

— Чё ты кричишь?

— По какому телефону звонишь?!

— Двадцать два, пятьсот пять.

— Ну? Какой капитал? Пидор ты ёбаный!

— Прожи… Прожиточного минимума!

— Ну, прожиточного.

— Ну а чё ты кричишь?

— Да ни хуя! А то соплю тебе разобью нахуй, сопляк ёбаный!

— Ты чё?

— Ты понял, да?!

— Я не понимаю куд…

— Всё затнись нахуй!

— Алё.

— Пидорас ёбаный!

— А чё я?

— Ты приедь сюда, я тебе бошку отверну!

— А какой адрес?

— Вот приедь сюда, я тебе бошку отверну, сопляк ёбаный!

— Да не надо.

— Ты понял, да?!

— За что?

— За всё!

— А чё я сделал?

— Сынок ёбаный!

— Чё с деньгами?

— Ты понял меня?!

— Чё с деньгами, я спрашиваю?

— Вот всё, какие то деньги, ёбаный пидорас.

— Кто?

— Ты!

— Почему?

— Всё, заткнись.

— Алё. Алё.

— Я щас ещё узнаю с какого ты телефона звонишь!

— Я звоню щас из офиса.

— С какого офиса?

— Находящейся по улице Красноармейской, четыре.

— Вот, номер твой телефон скажи мне.

— Алё.

— Скажи номер телефона своего.

— Зачем?

— А чтобы я приехал тебе моську набил нахуй.

— За что это?

— А за всё! Ты понял, да?

— Ничё не понял.

— Я тебе сказал, сынок.

— Что?

— Ты понял меня?

— Папа!

— Всё.

— Чё всё то?

— Ты давай номер телефона или сюда приезжай.

— А с деньгами как вопрос обстоит?

— С какими деньгами?!

— Которые я вложил.

— Куда ты вложил?!

— В капитал.

— В какой?

— Прожиточного минимума.

— Пидорас ёбаный!

— Что?

**Comment by DarkKeks** [comment]
Кричу

**Comment by lodthe** [comment]
done
