### ISSUE TITLE
Господа, будет оче круто, если кто-нибудь опять почекает тех по ТВиМСУ

### ISSUE THREAD

**Issue by BoloniniD** [hse-tex/hse-tex#142]
Я вроде как все доделал, но стиль кода в техе, да и в документе такой себе, а сам я прям красиво сделать не могу. + надо почекать это на ошибки и очепятки, наверняка еще остались.

**Comment by shoraii** [comment]
Пункт 7
![изображение](https://user-images.githubusercontent.com/26520464/97480497-8a247080-1964-11eb-82af-9a3598e609d4.png)

**Comment by BoloniniD** [comment]
Понял, исправляю

**Comment by LoDThe** [comment]
Ну, твимс закончился, поэтому закрываю :1st_place_medal:
