### ISSUE TITLE
Change social preview

### ISSUE THREAD

**Issue by LoDThe** [hse-tex/hse-tex#165]
Кто-нибудь хочет сделать нормальную картинку для превью репозитория?
Это изображение будет видно, например, когда вы в телеграме скидываете ссылку на репозиторий.

Сейчас показывается этот стыд:
![image](https://user-images.githubusercontent.com/4996880/102092579-43fe7000-3e31-11eb-9273-081e56d25911.png)

**Comment by DarkKeks** [comment]
Лучше же выпилить совсем

**Comment by LoDThe** [comment]
Удалил. И что теперь поставим?

**Comment by LoDThe** [comment]
Дефолтная норм.
