### ISSUE TITLE
1 курс 2й колок по линалу 6й вопрос 

### ISSUE THREAD

**Issue by Skovorp** [hse-tex/hse-tex#272]
![image](https://user-images.githubusercontent.com/46576943/118659371-1af85780-b7a2-11eb-805c-cf78a2b235a1.png)
Переход красной стрелки странный

Это бы означало что любые 2 лин оболочки базисных векторов, в сумме дают одну и ту же плоскость

**Comment by lodthe** [comment]
Вроде бы все валидно.

Две непересекащиеся линейные оболочки базисных векторов дают в сумме пространство над всеми этими векторами.

Не совсем понимаю, что ты хотел сказать. У любых двух линейных оболочек суммарная размерность может отличаться, поэтому они будут давать разные плоскости.

**Comment by lodthe** [comment]
U1 и U2 это не произвольные подпространства. В формулировке билета сказано, что U1 и U2 это подпространства у V

**Comment by Skovorp** [comment]
черт, я не заметил что они подпространства. Закрываю диспут
